query Quiz($slug: String) {
  quizzes(where: { slug: $slug }) {
    id
    title
    exam
    examTimeLimit
    pointsToPassExam
    questions {
      id
      question
      successText
      failText
      type
      answers {
        id
        answer
        correct
      }
    }
  }
}
